databaseChangeLog:
    - changeSet:
          id: account_id_pk
          author: alejandro.hernandez
          preConditions:
              - or:
                    - dbms:
                          type: mysql
          changes:
              - addPrimaryKey:
                    clustered: true
                    columnNames: id
                    constraintName: pk_account
                    tableName: account
                    validate: true
              - addAutoIncrement:
                    columnName: id
                    columnDataType: BIGINT
                    defaultOnNull: false
                    generationType: ALWAYS
                    incrementBy: 1
                    startWith: 1
                    tableName: account
    - changeSet:
          id: account_user_fk
          author: alejandro.hernnadez
          changes:
              - addForeignKeyConstraint:
                    baseColumnNames: user_id
                    baseTableName: account
                    constraintName: fk_account_user
                    deferrable: false
                    initiallyDeferred: false
                    referencedColumnNames: id
                    referencedTableName: user
    - changeSet:
          id: account_financial_entity_fk
          author: alejandro.hernnadez
          changes:
              - addForeignKeyConstraint:
                    baseColumnNames: financial_entity_id
                    baseTableName: account
                    constraintName: fk_account_financial_entity
                    deferrable: false
                    initiallyDeferred: false
                    referencedColumnNames: id
                    referencedTableName: financial_entity
