databaseChangeLog:
  - changeSet:
      id: budget_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addColumn:
            tableName: budget
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
      id: client_sequence_pk
      author: alejandro.hernandez
      dbms: oracle
      changes:
        - createSequence:
            cacheSize: 371717
            cycle: true
            dataType: int
            maxValue: 10000000
            incrementBy: 1
            ordered: true
            sequenceName: budget_seq
            startValue: 1
  - changeSet:
      id: budget_oracle_id_pk
      author: alejandro.hernandez
      dbms: oracle
      preConditions:
        - or:
            - dbms:
                type: oracle
      changes:
        - addColumn:
            tableName: budget
            columns:
              - column:
                  name: id
                  type: SERIAL
                  valueComputed: budget_seq.NEXTVAL
                  constraints:
                    nullable: false
                    primaryKey: true

  - changeSet:
      id: budget_category_fk
      author: alejandro.hernandez
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: category_id
            baseTableName: budget
            constraintName: fk_budget_category
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: category
        - changeSet:
            id: budget_system_category_fk
            author: alejandro.hernandez
            changes:
              - addForeignKeyConstraint:
                  baseColumnNames: system_category_id
                  baseTableName: budget
                  constraintName: fk_budget_system_category
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: system_category
        - changeSet:
            id: budget_user_fk
            author: alejandro.hernandez
            changes:
              - addForeignKeyConstraint:
                  baseColumnNames: user_id
                  baseTableName: budget
                  constraintName: fk_budget_user
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: user

  - changeSet:
      id: budget
      author: alejandro.hernandez
      changes:
      - addColumn:
            tableName: budget
            columns:
              - column:
                  name: warning_percentage
                  type: DECIMAL(18,12)
                  constraints:
                    nullable: false