databaseChangeLog:
  - changeSet:
      id: category_auto_increment
      author: alejandro.garcia
      dbms: mysql,h2
      changes:
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 91
            tableName: category
  - changeSet:
        id: category_sequence_pk
        author: alejandro.hernandez
        dbms: oracle
        changes:
            - createSequence:
                  cacheSize: 371717
                  catalogName: category
                  cycle: true
                  dataType: int
                  maxValue: 10000000
                  incrementBy: 1
                  ordered: true
                  sequenceName: category_seq_id
                  startValue: 1

  - changeSet:
      id: category_client_fk
      author: alejandro.hernandez
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: client_id
            baseTableName: category
            constraintName: fk_category_client
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: client
  - changeSet:
      id: category_parent_fk
      author: alejandro.hernandez
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: parent_id
            baseTableName: category
            constraintName: fk_category_parent
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: category
  - changeSet:
      id: category_user_fk
      author: alejandro.hernnadez
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: user_id
            baseTableName: category
            constraintName: fk_category_user
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: user