databaseChangeLog:
  - changeSet:
      id: client_role_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 1
            tableName: client_role
  - changeSet:
        id: client_role_sequence_pk
        author: alejandro.hernandez
        dbms: oracle
        changes:
            - createSequence:
                  cacheSize: 371717
                  cycle: true
                  dataType: int
                  maxValue: 10000000
                  incrementBy: 1
                  ordered: true
                  sequenceName: client_role_seq_id
                  startValue: 1