databaseChangeLog:
  - changeSet:
      id: client_profile_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addColumn:
            tableName: client_profile
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
      id: client_profile_sequence_pk
      author: alejandro.hernandez
      dbms: oracle
      changes:
        - createSequence:
            cacheSize: 371717
            cycle: true
            dataType: int
            maxValue: 10000000
            incrementBy: 1
            ordered: true
            sequenceName: client_profile_seq
            startValue: 1
  - changeSet:
      id: client_profile_oracle_id_pk
      author: alejandro.hernandez
      dbms: oracle
      preConditions:
        - or:
            - dbms:
                type: oracle
      changes:
        - addColumn:
            tableName: client_profile
            columns:
              - column:
                  name: id
                  type: SERIAL
                  valueComputed: client_profile_seq.NEXTVAL
                  constraints:
                    nullable: false
                    primaryKey: true

  - changeSet:
        id: client_profile_client_fk
        author: alejandro.hernandez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: client_id
                  baseTableName: client_profile
                  constraintName: fk_client_profile_client
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: client
