databaseChangeLog:
  - changeSet:
      id: client_role_id_pk
      author: alejandro.hernandez
      preConditions:
        - or:
            - dbms:
                type: mysql
      changes:
        - addPrimaryKey:
            clustered: true
            columnNames: id
            constraintName: pk_client_role
            tableName: client_role
            validate: true
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 1
            tableName: client_role