databaseChangeLog:
  - changeSet:
      id: client_role_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 1
            tableName: client_role