databaseChangeLog:
    - changeSet:
          id: financial_entity_id_pk
          author: alejandro.hernandez
          dbms: mysql,h2
          preConditions:
              - or:
                    - dbms:
                          type:  mysql,h2
          changes:
              - addAutoIncrement:
                    columnName: id
                    columnDataType: BIGINT
                    defaultOnNull: false
                    generationType: ALWAYS
                    incrementBy: 1
                    startWith: 1
                    tableName: financial_entity
    - changeSet:
          id: financial_entity_client_fk
          author: alejandro.hernandez
          changes:
              - addForeignKeyConstraint:
                    baseColumnNames: client_id
                    baseTableName: financial_entity
                    constraintName: fk_financial_entity_client
                    deferrable: false
                    initiallyDeferred: false
                    referencedColumnNames: id
                    referencedTableName: client