databaseChangeLog:
    - changeSet:
          id: financial_entity_id_pk
          author: alejandro.hernandez
          preConditions:
              - or:
                    - dbms:
                          type: mysql
          changes:
              - addPrimaryKey:
                    clustered: true
                    columnNames: id
                    constraintName: pk_financial_entity
                    schemaName: pfm_api
                    tableName: financial_entity
                    validate: true
              - addAutoIncrement:
                    columnName: id
                    columnDataType: BIGINT
                    defaultOnNull: false
                    generationType: ALWAYS
                    incrementBy: 1
                    startWith: 1
                    tableName: financial_entity
    - changeSet:
          id: financial_entity_client_fk
          author: alejandro.hernandez
          changes:
              - addForeignKeyConstraint:
                    baseColumnNames: client_id
                    baseTableName: financial_entity
                    constraintName: fk_financial_entity_client
                    deferrable: false
                    initiallyDeferred: false
                    referencedColumnNames: id
                    referencedTableName: client