databaseChangeLog:
    - changeSet:
          id: role_id_pk
          author: alejandro.hernandez
          dbms: mysql,h2
          preConditions:
              - or:
                - dbms:
                    type: mysql,h2
          changes:
            - addColumn:
                tableName:  role
                columns:
                  - column:
                      name: id
                      type: BIGINT
                      autoIncrement: true
                      constraints:
                        nullable: false
                        primaryKey: true
    - changeSet:
        id: role_sequence_pk
        author: alejandro.hernandez
        dbms: oracle
        changes:
          - createSequence:
              cacheSize: 371717
              cycle: true
              dataType: int
              maxValue: 10000000
              incrementBy: 1
              ordered: true
              sequenceName: role_seq
              startValue: 1
    - changeSet:
        id: role_oracle_id_pk
        author: alejandro.hernandez
        dbms: oracle
        preConditions:
          - or:
              - dbms:
                  type: oracle
        changes:
          - addColumn:
              tableName: role
              columns:
                - column:
                    name: id
                    type: SERIAL
                    valueComputed: role_seq.NEXTVAL
                    constraints:
                      nullable: false
                      primaryKey: true