databaseChangeLog:
    - changeSet:
          id: role_id_pk
          author: alejandro.hernandez
          preConditions:
              - or:
                - dbms:
                    type: mysql
          changes:
              - addPrimaryKey:
                    clustered: true
                    columnNames: id
                    constraintName: pk_role
                    tableName: role
                    validate: true
              - addAutoIncrement:
                    columnName: id
                    columnDataType: BIGINT
                    defaultOnNull: false
                    generationType: ALWAYS
                    incrementBy: 1
                    startWith: 1
                    tableName: role
