databaseChangeLog:
  - changeSet:
      id: system_category_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addColumn:
            tableName: system_category
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
      id: system_category_sequence_pk
      author: alejandro.hernandez
      dbms: oracle
      changes:
        - createSequence:
            cacheSize: 371717
            cycle: true
            dataType: int
            maxValue: 10000000
            incrementBy: 1
            ordered: true
            sequenceName: system_category_seq
            startValue: 1
  - changeSet:
      id: system_category_oracle_id_pk
      author: alejandro.hernandez
      dbms: oracle
      preConditions:
        - or:
            - dbms:
                type: oracle
      changes:
        - addColumn:
            tableName: system_category
            columns:
              - column:
                  name: id
                  type: SERIAL
                  valueComputed: system_category_seq.NEXTVAL
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
        id: system_category_parent_fk
        author: alejandro.hernandez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: parent_id
                  baseTableName: system_category
                  constraintName: fk_system_category_parent
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: system_category