databaseChangeLog:
  - changeSet:
      id: transaction_id_pk
      author: alejandro.hernandez
      preConditions:
        - or:
            - dbms:
                type: mysql
      changes:
        - addPrimaryKey:
            clustered: true
            columnNames: id
            constraintName: pk_transaction
            tableName: transaction
            validate: true
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 1
            tableName: transaction
  - changeSet:
        id: transaction_account_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: account_id
                  baseTableName: transaction
                  constraintName: fk_transaction_account
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: account
  - changeSet:
        id: transaction_system_category_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: system_category_id
                  baseTableName: transaction
                  constraintName: fk_transaction_system_category
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: system_category
  - changeSet:
        id: transaction_category_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: category_id
                  baseTableName: transaction
                  constraintName: fk_transaction_category
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: category