databaseChangeLog:
  - changeSet:
      id: transaction_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addColumn:
            tableName: transaction
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
      id: transaction_sequence_pk
      author: alejandro.hernandez
      dbms: oracle
      changes:
        - createSequence:
            cacheSize: 371717
            cycle: true
            dataType: int
            maxValue: 10000000
            incrementBy: 1
            ordered: true
            sequenceName: transaction_seq
            startValue: 1
  - changeSet:
      id: transaction_oracle_id_pk
      author: alejandro.hernandez
      dbms: oracle
      preConditions:
        - or:
            - dbms:
                type: oracle
      changes:
        - addColumn:
            tableName: transaction
            columns:
              - column:
                  name: id
                  type: SERIAL
                  valueComputed: transaction_seq.NEXTVAL
                  constraints:
                    nullable: false
                    primaryKey: true

  - changeSet:
        id: transaction_account_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: account_id
                  baseTableName: transaction
                  constraintName: fk_transaction_account
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: account
  - changeSet:
        id: transaction_system_category_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: system_category_id
                  baseTableName: transaction
                  constraintName: fk_transaction_system_category
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: system_category
  - changeSet:
        id: transaction_category_fk
        author: alejandro.hernnadez
        changes:
            - addForeignKeyConstraint:
                  baseColumnNames: category_id
                  baseTableName: transaction
                  constraintName: fk_transaction_category
                  deferrable: false
                  initiallyDeferred: false
                  referencedColumnNames: id
                  referencedTableName: category