databaseChangeLog:
  - changeSet:
      id: user_id_pk
      author: alejandro.hernandez
      dbms: mysql,h2
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addColumn:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
        id: user_sequence_pk
        author: alejandro.hernandez
        dbms: oracle
        changes:
          - createSequence:
              cacheSize: 371717
              cycle: true
              dataType: int
              maxValue: 10000000
              incrementBy: 1
              ordered: true
              sequenceName: user_seq
              startValue: 1
  - changeSet:
      id: user_oracle_id_pk
      author: alejandro.hernandez
      dbms: oracle
      preConditions:
        - or:
            - dbms:
                type: oracle
      changes:
        - addColumn:
            tableName: users
            columns:
              - column:
                  name: id
                  type: SERIAL
                  valueComputed: user_seq.NEXTVAL
                  constraints:
                    nullable: false
                    primaryKey: true

  - changeSet:
      id: user_client_fk
      author: alejandro.hernnadez
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: client_id
            baseTableName: users
            constraintName: fk_user_client
            deferrable: false
            initiallyDeferred: false
            referencedColumnNames: id
            referencedTableName: client