databaseChangeLog:
  - changeSet:
      id: user_id_pk
      author: alejandro.hernandez
      preConditions:
        - or:
            - dbms:
                type:  mysql,h2
      changes:
        - addPrimaryKey:
            clustered: true
            columnNames: id
            constraintName: pk_user
            tableName: user
            validate: true
        - addAutoIncrement:
            columnName: id
            columnDataType: BIGINT
            defaultOnNull: false
            generationType: ALWAYS
            incrementBy: 1
            startWith: 1
            tableName: user
