micronaut:
  application:
    name: finerio-pfm-api
    max: 50
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: secret01234567890ABCDEFGHIJKLMNO
  server:
    port: 8080
    cors:
      enabled: true
dataSource:
  username: root
  password: dinerio73
  url: jdbc:mysql://127.0.0.1:3306/pfm_develop?verifyServerCertificate=false&useSSL=true
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/databaseChangeLog.yaml'
