micronaut:
  application:
    name: finerio-pfm-api
    max: 50
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: secret01234567890ABCDEFGHIJKLMNO
dataSource:
  username: root
  password: dinerio73
  url: jdbc:mysql://127.0.0.1:3306/pfm_develop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  dbCreate: update
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/databaseChangeLog.yaml'