micronaut:
  application:
    name: finerio-pfm-api
    max: 50
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: secret01234567890ABCDEFGHIJKLMNO
  server:
    port: 8080
    cors:
      enabled: true
dataSource:
  url: jdbc:oracle:thin:@oracle-test.cnl1kw96ddli.us-east-2.rds.amazonaws.com:1521:ORCL
  driverClassName: oracle.jdbc.driver.OracleDriver
  username: admin
  password: Dyb5kX3zf2as6ZGJcLw8Q7gRHVn7d
  dialect: ORACLE
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/databaseChangeLog.yaml'
categorizer:
  url: 'http://ec2-3-12-253-103.us-east-2.compute.amazonaws.com:8085'
  username: '9j7gnsHf9Nn6kWnmx5cEFtcHq962jyFzbSj7ULkYRXSadrhjSS'
  password: 'zehx6XCAZXpsxZAm2UBQhteabjUED86EvtqfL2j54qQzBawTeGz9m87dAjEeCuRzPcmstf96jDY6Fbap2NFaAz3YxkVMaDAZxQy8'
endpoints:
  health:
    enabled: true
    sensitive: true
